kumaUrl: "http://kuma.batchelorparty.com"

resyncInterval: "300"

logLevel: "INFO"

credentials:
  existingSecret: "my-kuma-secret"

staticMonitors:
  enabled: true
  monitors:
    - name: Portfolio Website
      type: http
      url: https://itsmeganificent.com/
      interval: 600
      conditions: []
