ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: kuma.batchelorparty.com
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
