ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    uptime-kuma.io/monitor: "true"
  hosts:
    - host: plex.batchelorparty.com
      paths:
        - path: /
          pathType: Prefix

dnsPolicy: ClusterFirstWithHostNet

extraVolumes:
  - name: plex-media-nfs
    nfs:
      server: 192.168.98.150  # Replace with your TrueNAS IP
      path: /mnt/BatchFlix/BatFlixShare # Replace with your NFS Export path
      readOnly: true        # Recommended for media libraries
  - name: dev-dri
    hostPath:
      path: /dev/dri

extraVolumeMounts:
  - name: plex-media-nfs
    mountPath: /data/media
  - name: dev-dri
    mountPath: /dev/dri

extraEnv:
  - ADVERTISE_IP: "http://plex.batchelorparty.com:80"
  - name: PLEX_CLAIM
    valueFrom:
      secretKeyRef:
        name: plex-secrets
        key: claim-token
  - name: PLEX_UID
    value: "972"
  - name: PLEX_GID
    value: "972"

podSecurityContext:
  supplementalGroups: [39, 105]
