ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    uptime-kuma.io/monitor: "true"
  hosts:
    - host: plex.batchelorparty.com
      paths:
        - path: /
          pathType: Prefix

dnsPolicy: ClusterFirstWithHostNet

extraVolumes:
  - name: plex-media-nfs
    nfs:
      server: 192.168.98.150  # Replace with your TrueNAS IP
      path: /mnt/BatchFlix/BatFlixShare # Replace with your NFS Export path
      readOnly: true        # Recommended for media libraries
  - name: dev-dri
    hostPath:
      path: /dev/dri

extraVolumeMounts:
  - name: plex-media-nfs
    mountPath: /data/media
  - name: dev-dri
    mountPath: /dev/dri

extraEnv:
  PLEX_UID: "972"
  PLEX_GID: "972"

pms:
  claimSecret:
    name: "plex-secrets"
    key: "claim-token"

podSecurityContext:
  supplementalGroups: [39, 105]

service:
  type: LoadBalancer
  externalTrafficPolicy: Local
  annotations:
    metallb.universe.tf/address-pool: plex-pool
  ports:
    - name: plex
      port: 32400
      targetPort: 32400
      protocol: TCP
