# values for the small-hack home-assistant chart
# https://github.com/small-hack/home-assistant-chart

service:
  port: 80

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: ha.batchelorparty.com
      paths:
        - path: /
          pathType: Prefix

image:
  tag: "2026.2.3"

strategy:
  type: Recreate

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: "longhorn"

homeAssistant:
  configuration: |-
    homeassistant:
      time_zone: America/Chicago
      temperature_unit: F
      unit_system: US customary

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16 # Pod Network (Traefik's IP is here)
        - 10.43.0.0/16 # Service Network
        - 192.168.98.0/24 # Your Local Network (Optional, but helpful)

    # Loads default set of integrations. Do not remove.
    default_config:

    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

  setupHacsJobs:
    enabled: true

# examples for adding USB devices or other host volumes
#extraVolumes:
#  - name: usb
#    hostPath:
#      path: "/dev/serial/by-id/usb-..."
#      type: CharDevice
#extraVolumeMounts:
#  - name: usb
#    mountPath: /dev/ttyACM0
#    readOnly: true
