# values for the small-hack home-assistant chart
# https://github.com/small-hack/home-assistant-chart

service:
  port: 80

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: ha.batchelorparty.com
      paths:
        - path: /
          pathType: Prefix

readinessProbe:
  initialDelaySeconds: 30 # Give it 30s before even checking
  periodSeconds: 10
  failureThreshold: 10 # Allow 10 failures (100s total) before giving up

livenessProbe:
  initialDelaySeconds: 60 # Be even more generous with liveness to avoid restart loops
  periodSeconds: 20
  failureThreshold: 5

image:
  tag: "2026.2.3"

strategy:
  type: Recreate

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: "longhorn"

# extraVolumes:
#   - name: ha-scripts
#     configMap:
#       name: ha-config-scripts

# extraVolumeMounts:
#   - name: ha-scripts
#     mountPath: /config/scripts.yaml
#     subPath: scripts.yaml
#     readOnly: true

homeAssistant:
  configuration: |-
    homeassistant:
      time_zone: America/Chicago
      temperature_unit: F
      unit_system: us_customary

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/24 # Traefik's IP range (optional, but recommended for accurate client IP logging)
        - 10.42.0.0/16 # Pod Network (Traefik's IP is here)
        - 10.43.0.0/16 # Service Network
        - 192.168.98.0/24 # Your Local Network (Optional, but helpful)

    # Loads default set of integrations. Do not remove.
    default_config:

    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
  scripts: |
    # default scripts content
    # add your scripts here
    # Example:
    # my_script:
    #   sequence:
    #     - service: light.turn_on
    #       target:
    #         entity_id: light.living_room
  setupHacsJobs:
    enabled: true

# examples for adding USB devices or other host volumes
#extraVolumes:
#  - name: usb
#    hostPath:
#      path: "/dev/serial/by-id/usb-..."
#      type: CharDevice
#extraVolumeMounts:
#  - name: usb
#    mountPath: /dev/ttyACM0
#    readOnly: true
