---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd

spec:
  project: apps

  sources:
    - repoURL: ghcr.io/m0nsterrr/helm-charts
      chart: homepage
      targetRevision: 4.11.*
      helm:
        valueFiles:
          - $HomeInfra/gitops/apps/homepage/values.yaml

    - repoURL: https://github.com/TheBatchelorFamily/HomeInfra.git
      targetRevision: main
      ref: HomeInfra

    - repoURL: https://github.com/TheBatchelorFamily/HomeInfra.git
      targetRevision: main
      path: gitops/apps/homepage/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: homepage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
