---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant

  sources:
    - repoURL: http://pajikos.github.io/home-assistant-helm-chart/
      chart: home-assistant
      targetRevision: 0.3.44
      helm:
        valueFiles:
          - $HomeInfra/gitops/apps/home-assistant/values.yaml

    - repoURL: git@github.com:TheBatchelorFamily/HomeInfra.git
      targetRevision: main
      ref: HomeInfra

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
