apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/TheBatchelorFamily/HomeInfra.git
    targetRevision: main
    path: gitops/apps/home-assistant

    chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts/
    targetRevision: 3.5.1

    helm:
      releaseName: home-assistant
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
