---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd

  annotations:
    # 1. Define the image to monitor (alias = portfolio)
    argocd-image-updater.argoproj.io/image-list: portfolio=fiercekitti/portfolio_website
    
    # 2. Use the 'latest' strategy to grab the newest tag by creation date
    argocd-image-updater.argoproj.io/portfolio.update-strategy: digest

spec:
  project: apps

  source:
    repoURL: https://github.com/TheBatchelorFamily/HomeInfra.git
    targetRevision: main
    path: gitops/apps/portfolio/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
