ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    uptime-kuma.io/monitor: "true"
  host: longhorn.batchelorparty.com
  path: /
  pathType: Prefix

persistence:
  defaultClass: true
  defaultClassReplicaCount: 3
  recurringJobSelector:
    enable: true
    jobList: '[{"name":"daily-backup", "isDefault":true}]'

longhornUI:
  replicas: 1

defaultBackupStore:
  # -- Endpoint used to access the default backupstore. (Options: "NFS", "CIFS", "AWS", "GCP", "AZURE")
  backupTarget: nfs://192.168.98.150:/mnt/BatchFlix/k3s/Longhorn
