# Default Pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.98.210-192.168.98.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-adv
  namespace: metallb-system

# Traefik Pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: traefik-pool
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
    - 192.168.98.202/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: traefik-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - traefik-pool

# Plex Pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: plex-pool
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
    - 192.168.98.203/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: plex-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - plex-pool
