ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    uptime-kuma.io/monitor: "true"
  hosts:
    - host: box.batchelorparty.com
      paths:
        - path: /
          pathType: Prefix

postgresql:
  enabled: false

env:
  HBOX_DATABASE_SQLITE_PATH: /data/homebox.db?_pragma=busy_timeout=999&_pragma=journal_mode=WAL&_fk=1

persistence:
  storageClass: "longhorn"